### ISSUE TITLE
SSL for PHP 5.2 box

### ISSUE THREAD

**Issue by kostajh** [tierra/wp-vagrant#21]
Any tips for configuring SSL for the PHP 5.2 box? I notice you've intentionally only enabled it for the PHP 5.3+ boxes, so I'm wondering if you ran into any particularly painful areas with trying to get this working for PHP 5.2.

**Comment by tierra** [comment]
It's been a long time since the box was put together, and I don't really remember what the roadblock was for getting it working, but I seem to recall it being mostly a dead end, and definitely not anything worth struggling with instead of just testing HTTPS-related functionality within one of the PHP 5.3+ boxes.

**Comment by kostajh** [comment]
Yeah, fair enough. Ok, thanks for your reply!

On Mon, Sep 21, 2015, at 09:34 PM, Bryan Petty wrote:
> It's been a long time since the box was put together, and I don't
> really remember what the roadblock was for getting it working, but I
> seem to recall it being mostly a dead end, and definitely not anything
> worth struggling with instead of just testing HTTPS-related
> functionality within one of the PHP 5.3+ boxes.


> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/tierra/wp-vagrant/issues/21#issuecomment-142156001
