### ISSUE TITLE
phpmyadmin

### ISSUE THREAD

**Issue by aagjalpankaj** [tierra/wp-vagrant#23]
I performed following steps to access phpmyadmin.

1. vagrant up wordpress-php52
2. vagrant ssh wordpress-php52
3. sudo apt-get install phpmyadmin
4. sudo ln -s /usr/share/phpmyadmin /vagrant/wordpress/build/
5. sudo nano /etc/apache2/apache2.conf and appended line "Include /etc/phpmyadmin/apache.conf"
6. Opened link http://wordpress-php52.local/phpmyadmin into browser

phpmyadmin not working. Where am I going wrong?

**Comment by tierra** [comment]
That's really a question outside the scope of this project, but I would personally recommend that if you need something like phpMyAdmin, that you consider just moving [Adminer](https://www.adminer.org/) into your `/vagrant/wordpress/build/` directory since it's a simple one-php-file-application that's ridiculously easy to install and use.

**Comment by tierra** [comment]
Also, it might help to try this out on one of the more modern boxes provided like the PHP 5.3, 5.4, or 5.5 boxes. The PHP 5.2 box is incredibly outdated and I definitely no longer bother providing support for it specifically (even though I still leave the box in the repo).
